@startuml
skinparam Style strictuml
skinparam SequenceMessageAlignment center
left to right direction

actor Cliente as cli
actor Barbero as bbo
actor Administrador as admin
rectangle "Sistema" {
    usecase "crea su cuenta" as UC1
    usecase "inicia sesion" as UC2
    usecase "Recuperar contraseña" as UC3
    usecase "Rectifica los datos" as UC4
    usecase "Indica los productos que desea comprar " as UC5
    usecase "registrar productos" as UC6
    usecase "Registrar productos" as UC7
    usecase "Calcula y muestra el precio" as UC8
    usecase "Realiza pago del producto" as UC9
    usecase "Verifica el pago" as UC10
    usecase "Verifica el pago" as UC11
    usecase "Genera estadisticas de las ventas" as UC12
    usecase "Añadir productos al carrito" as UC13
    usecase "Reservar turnos" as UC14
    usecase "seleccionar barbero de preferencia" as UC15
    usecase "Selecciona servicio" as UC16
    usecase "Selecciona hora y fecha" as UC17
    usecase "Cancelar cita" as UC18
    usecase "asigna disponibilidad" as UC19
    usecase "Acepta el turno" as UC20
    usecase "Genera recordatorio" as UC21
    usecase "Editar perfil" as UC22
    usecase "Cerrar sesion" as UC23

    cli --> UC1
    cli --> UC2
    cli --> UC3
    cli --> UC5
    cli --> UC9
    cli --> UC13
    cli --> UC14
    cli --> UC15
    cli --> UC16
    cli --> UC17
    cli --> UC18
    cli --> UC22
    cli --> UC23 

    UC10 --> UC11: Include
    UC11 --> UC12: Include
    UC6 --> UC7: Include
    UC7 --> UC8: Include
    UC1 --> UC4: Include
    UC2 --> UC4: Include
    UC3 --> UC4: Include
    UC20 --> UC21: Include



    bbo --> UC23
    bbo --> UC2
    bbo --> UC19
    bbo --> UC20



    admin --> UC2
    admin --> UC6  
    admin --> UC10
    admin --> UC20
    admin --> UC23 
    
   
}
@enduml